version: '3.5'
services:

  nginx:
    image: "nginx:alpine"
    ports:
      - ${NGINX_PORT_HTTP}:80
      - 443:443
    volumes:
        - ./nginx/sites/:/etc/nginx/conf.d/
        - ./.data/logs-nginx/:/var/log/nginx
        - ${WEB_PATH}:/var/www/html
    environment:
        TZ: "Asia/Shanghai"
    depends_on:
        - php
    restart: unless-stopped

# PHP-FPM
  php:
    image: "1300775666/php:v2"
    volumes:
      - ${WEB_PATH}:/var/www/html
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    restart: unless-stopped

# MySQL
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    restart: unless-stopped 
